export const menuItems = [{
        id: 1,
        label: "Menu",
        isTitle: true,
        user: [],
    },
    {
        id: 2,
        label: "Home",
        icon: "bx-home-circle",
        link: "/home",
        component: "Home/Index",
        name: "Home",
        user: [],
    },
    {
        id: 10,
        label: "Qualifiers",
        icon: "bx-id-card",
        link: "/qualifiers",
        component: "Qualifiers/Index",
        name: "Qualifiers",
        user: [],
    },
    {
        id: 11,
        label: "Scholars",
        icon: "bx-group",
        link: "/scholars",
        name: "Scholars",
        component: "Scholars/Index",
        user: [],
    },
    {
        id: 12,
        label: "Enrollments",
        icon: "bxs-folder-open",
        link: "/enrollments",
        component: "Enrollments/Index",
        name: "Enrollments",
        user: [],
    },
    {
        id: 12,
        label: "Financial Benefits",
        icon: "bx-credit-card-front",
        link: "/benefits",
        component: "Benefits/Index",
        name: "Benefits",
        user: [],
    },
    {
        id: 13,
        label: "Insights",
        icon: "bx-line-chart",
        link: "/insights",
        component: "Insights/Index",
        name: "Insights",
        user: [],
    },
    // {
    //     id: 3,
    //     label: "Users",
    //     icon: "bxs-user-circle",
    //     link: "/users",
    //     component: "Users/Index",
    //     name: "Users",
    //     user: ['Super Administrator'],
    // },
    // {
    //     id: 4,
    //     label: "Schools",
    //     icon: "bxs-school",
    //     link: "/schools",
    //     component: "Schools/Index",
    //     name: "Schools",
    //     user: ['Super Administrator'],
    // },

    // {
    //     id: 5,
    //     label: "Downloads",
    //     icon: "bx-cloud-download",
    //     link: "/downloads",
    //     component: "Downloads/Index",
    //     user: ['Super Administrator'],
    // },
    // {
    //     id: 6,
    //     label: "Logs",
    //     icon: "bx-message-square-dots",
    //     link: "/logs",
    //     component: "Logs/Index",
    //     user: ['Super Administrator'],
    // }
];