export const menuItems = [{
        id: 1,
        label: "Menu",
        isTitle: true,
        user: [],
    },
    {
        id: 2,
        label: "Home",
        icon: "bx-home-circle",
        link: "/home",
        component: "Home/Index",
        name: "Home",
        user: ['Scholarship Coordinator'],
    },
    {
        id: 10,
        label: "Qualifiers",
        icon: "bx-id-card",
        link: "/qualifiers",
        component: "Qualifiers/Index",
        name: "Qualifiers",
        user: ['Scholarship Coordinator'],
    },
    {
        id: 11,
        label: "Scholars",
        icon: "bx-group",
        link: "/scholars",
        name: "Scholars",
        component: "Scholars/Index",
        user: ['Scholarship Coordinator'],
    },
    {
        id: 12,
        label: "Enrollments",
        icon: "bxs-folder-open",
        link: "/enrollments",
        component: "Enrollments/Index",
        name: "Enrollments",
        user: ['Scholarship Coordinator'],
    },
    // {
    //     id: 12,
    //     label: "Financial Benefits",
    //     icon: "bx-credit-card-front",
    //     link: "/benefits",
    //     component: "Benefits/Index",
    //     name: "Benefits",
    //     user: ['Scholarship Coordinator'],
    // },
    {
        id: 191,
        label: "Financial Benefits 2",
        icon: "bx-credit-card-front",
        link: "/benefits2",
        component: "Benefits2/Index",
        name: "Benefits2",
        user: ['Scholarship Coordinator'],
    },
    {
        id: 123,
        label: "Accounting",
        icon: "bxs-wallet",
        link: "/accounting",
        component: "Accounting/Index",
        name: "Accounting",
        user: ['Scholarship Coordinator'],
    },
    {
        id: 4,
        label: "Schools",
        icon: "bxs-school",
        link: "/schools",
        component: "Schools/Index",
        name: "Schools",
        user: ['Scholarship Coordinator'],
    },
    {
        id: 13,
        label: "Insights",
        icon: "bx-line-chart",
        link: "/insights",
        component: "Insights/Index",
        name: "Insights",
        user: ['Scholarship Coordinator'],
    },
    {
        id: 3,
        label: "Users",
        icon: "bxs-user-circle",
        link: "/users",
        component: "Users/Index",
        name: "Users",
        user: ['Scholarship Coordinator'],
    },

    {
        id: 5,
        label: "Downloads",
        icon: "bx-cloud-download",
        link: "/downloads",
        component: "Downloads/Index",
        user: ['Scholarship Coordinator'],
    },
    {
        id: 6,
        label: "Logs",
        icon: "bx-message-square-dots",
        link: "/logs",
        component: "Logs/Index",
        user: ['Super Administrator'],
    }
];