export const menuItems = [{
        id: 1,
        label: "Home",
        icon: "bx-home",
        color: "text-warning",
        link: "/home",
        component: "Home/Index",
        name: "Scholarship/Index",
        user: [],
    }, {
        id: 2,
        label: "Profile Information",
        icon: "bx-user-circle",
        color: "text-primary",
        link: "/profile",
        component: "Scholarship/Index",
        name: "Scholarship/Profile",
        user: [],
    }, {
        id: 3,
        label: "Financial Benefits",
        icon: "bx-money",
        color: "text-danger",
        link: "/financial-benefits",
        component: "Home/Index",
        name: "Scholarship/Financial",
        user: [],
    },
    {
        id: 4,
        label: "Enrollment Information",
        icon: "bxs-school",
        color: "text-success",
        link: "/education",
        component: "Home/Index",
        name: "Scholarship/Education",
        user: [],
    },
    {
        id: 5,
        label: "Employment History",
        icon: "bx-user-pin",
        color: "text-info",
        link: "/employment",
        component: "Home/Index",
        name: "Scholarship/Employment",
        user: [],
    },
    {
        id: 2,
        label: "Prospectus",
        icon: "bx-notepad",
        color: "text-secondary",
        link: "/prospectus",
        component: "Home/Index",
        name: "Scholarship/Prospectus",
        user: [],
    }
];